# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Car_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#region imports
from PyQt5 import QtCore, QtGui, QtWidgets
#endregion


#region generated GUI class
class Ui_Form(object):
    def setupUi(self, Form):
        # Chat GPT helped me write this function.
        """
        Build the Qt widgets, layouts, and default values for the form.

        Args:
            Form: QWidget that receives the generated interface.

        Returns:
            None.
        """
        Form.setObjectName("Form")
        Form.resize(1143, 959)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grp_Inputs = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_Inputs.sizePolicy().hasHeightForWidth())
        self.grp_Inputs.setSizePolicy(sizePolicy)
        self.grp_Inputs.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grp_Inputs.setFont(font)
        self.grp_Inputs.setFlat(False)
        self.grp_Inputs.setObjectName("grp_Inputs")
        self.gridLayout = QtWidgets.QGridLayout(self.grp_Inputs)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.le_k2 = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_k2.sizePolicy().hasHeightForWidth())
        self.le_k2.setSizePolicy(sizePolicy)
        self.le_k2.setMinimumSize(QtCore.QSize(75, 0))
        self.le_k2.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_k2.setFont(font)
        self.le_k2.setObjectName("le_k2")
        self.gridLayout.addWidget(self.le_k2, 5, 1, 1, 1)
        self.le_tmax = QtWidgets.QLineEdit(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.le_tmax.sizePolicy().hasHeightForWidth())
        self.le_tmax.setSizePolicy(sizePolicy)
        self.le_tmax.setMinimumSize(QtCore.QSize(75, 0))
        self.le_tmax.setMaximumSize(QtCore.QSize(150, 16777215))
        self.le_tmax.setObjectName("le_tmax")
        self.gridLayout.addWidget(self.le_tmax, 7, 1, 1, 1)
        self.lbl_CarSpeed = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_CarSpeed.sizePolicy().hasHeightForWidth())
        self.lbl_CarSpeed.setSizePolicy(sizePolicy)
        self.lbl_CarSpeed.setObjectName("lbl_CarSpeed")
        self.gridLayout.addWidget(self.lbl_CarSpeed, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_m2 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_m2.sizePolicy().hasHeightForWidth())
        self.lbl_m2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_m2.setFont(font)
        self.lbl_m2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_m2.setObjectName("lbl_m2")
        self.gridLayout.addWidget(self.lbl_m2, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.lbl_k2 = QtWidgets.QLabel(self.grp_Inputs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_k2.sizePolicy().hasHeightForWidth())
        self.lbl_k2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_k2.setFont(font)
        self.lbl_k2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
